# ------------------------------------------------------
# Page tree
# ------------------------------------------------------
nav:

  - ðŸŽ“ Astra Tutorials:
    - ðŸ  Home: index.md
    - Astra Core:
      - â€£ Create Token: pages/astra/create-token.md
    - AstraDB:
      - â€£ Create Database: pages/astra/create-instance.md
      - â€£ Secure Connect Bundle: pages/astra/download-scb.md
      - â€£ Resume a database: pages/astra/resume-db.md
      - â€£ Multi Regions: pages/astra/multi-regions.md
      - â€£ CQL Proxy: pages/astra/cqlproxy.md
      - â€£ FAQ: pages/astra/faq.md
    - Astra Steaming:
      - â€£ Create Topic: pages/astra/create-topic.md
   
  - ðŸ“¥ Data Management:
    - ðŸ  Home: pages/data/index.md
    - Load Data:
      - â€£ Astra Data Loader: pages/data/load/astra-data-loader.md
      - â€£ DSBulk: pages/data/load/dsbulk.md
      - â€£ NoSQL Bench: pages/data/load/nosqlbench.md
    - Explore Data:
      - â€£ Cqlsh: pages/data/explore/cqlsh.md
      - â€£ Netflix Data Explorer : pages/data/explore/netflix-data-explorer.md
      - â€£ Datagrip: pages/data/explore/datagrip.md
      - â€£ DBSchema: pages/data/explore/dbschema.md
      - â€£ DBeaver: pages/data/explore/dbeaver.md
      - â€£ MindDB: pages/data/explore/minddb.md
      - â€£ TablePlus: pages/data/explore/tableplus.md
    - Data Modelling:
      - â€£ Kashliev KDM: http://kdm.kashliev.com/
      
  - ðŸ› ï¸ Develop:
    - ðŸ  List: pages/develop/index.md
    - Stargate Apis:
      - â€¢ REST: pages/develop/api/rest.md
      - â€¢ Document: pages/develop/api/document.md
      - â€¢ graphQL: pages/develop/api/graphql.md
      - â€¢ gRPC: pages/develop/api/grpc.md
    - Languages:
      - â€¢ Java: pages/develop/languages/java.md
      - â€¢ Javascript: pages/develop/languages/javascript.md
      - â€¢ Python: pages/develop/languages/python.md
      - â€¢ GoLang: pages/develop/languages/go.md
      - â€¢ CSharp: pages/develop/languages/csharp.md
      - â€¢ Scala: pages/develop/languages/scala.md
      - â€¢ Rust: pages/develop/languages/rust.md
    - Frameworks:
      - â€¢ Spring: pages/develop/frameworks/spring.md
      - â€¢ Quarkus: pages/develop/frameworks/quarkus.md
      - â€¢ Micronaut: pages/develop/frameworks/micronaut.md
  
  - ðŸ“¦ Tools:
    - ðŸ“¦ Tools List: pages/tools/index.md
    - Developers IDE:
      - â€¢ IntelliJ : todo.md
      - â€¢ Eclipse : todo.md
      - â€¢ VSCode : todo.md
      - â€¢ Gitpod : todo.md
    - Notebooks:
      - â€¢ Jupyter Notebooks : todo.md
      - â€¢ DataStax Studio : todo.md
      - â€¢ Apache Zeppelin : todo.md
    - Integration Middlewares:
      - â€¢ Apache Airflow : pages/tools/workflows/apache-airflow.md
      - â€¢ Apache Nifi : todo.md
      - â€¢ Apache Spark : todo.md
      - â€¢ Pentaho Data Integration : todo.md
      - â€¢ Temporal : todo.md
      
# ------------------------------------------------------
# Settings
# ------------------------------------------------------

# Project information
site_name: Awesome Astra
site_url: https://awesome-astra.github.io
site_author: Cedrick Lunven
site_description: >-
 Your Wiki to implement Awesome Applications with Astra

# Repository
repo_name: awesome-astra/docs
repo_url: https://github.com/awesome-astra/docs
edit_uri: ""

# Theme
theme:
 name: material
 language: en
 features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
 palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

 #favicon: assets/favicon.png
 #icon:
 #   logo: docs/img/logo-go.png
 
 include_search_page: false
 search_index_only: true

# Mardown Support
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - fontawesome_markdown
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  #- pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search

# Customization
extra:
  analytics:
    provider: google
    property: G-ZMZXZME49E
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCAIQY251avaMv7bBv5PCo-A
    - icon: fontawesome/brands/github
      link: https://github.com/clun
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/clunven
    - icon: fontawesome/brands/discord
      link: https://dtsx.io/discord

    
          