# ------------------------------------------------------
# Page tree
# ------------------------------------------------------
nav:
  - index.md
  - Get Started:
    - Getting Started With Astra: pages/astra/index.md
    - Astra Core:
      - â€£ Create Account: pages/astra/create-account.md
      - â€£ Create Token: pages/astra/create-token.md
      - â€£ Astra CLI: pages/astra/astra-cli.md
      - â€£ FAQ: pages/astra/faq.md
    - Astra DB:
      - â€£ Create Database: pages/astra/create-instance.md
      - â€£ Secure Connect Bundle: pages/astra/download-scb.md
      - â€£ Resume a database: pages/astra/resume-db.md
      - â€£ Multi Regions: pages/astra/multi-regions.md
      - â€£ CQL Proxy: pages/astra/cqlproxy.md
    - Astra Streaming:
      - â€£ Create Topic: pages/astra/create-topic.md
      - â€£ CDC for Astra Streaming: pages/astra/cdc-for-astra.md
    - Explore Stargate:
      - â€£ HTTPie: pages/astra/astra-httpie.md

  - Manage Data:
    - Home: pages/data/index.md
    - Load Data:
      - â€£ Astra Data Loader: pages/data/load/astra-data-loader.md
      - â€£ DSBulk: pages/data/load/dsbulk.md
      - â€£ NoSQL Bench: pages/data/load/nosqlbench.md
    - Explore Data:
      - â€£ Cqlsh: pages/data/explore/cqlsh.md
      - â€£ Netflix Data Explorer : pages/data/explore/netflix-data-explorer.md
      - â€£ Datagrip: pages/data/explore/datagrip.md
      - â€£ DBSchema: pages/data/explore/dbschema.md
      - â€£ DBeaver: pages/data/explore/dbeaver.md
      - â€£ Grafana: pages/tools/integration/grafana.md
      - â€£ MindsDB: pages/data/explore/mindsdb.md
      - â€£ Presto: pages/data/explore/presto.md
      - â€£ Tableau: pages/data/explore/tableau.md
      - â€£ TablePlus: pages/data/explore/tableplus.md
      - â€£ Trino: pages/data/explore/trino.md
    - Data Modelling:
      - â€£ Kashliev KDM: http://kdm.kashliev.com/

  - Developers:
    - List: pages/develop/index.md
    - SDK:
      - â€¢ Astra SDK Java: pages/develop/sdk/astra-sdk-java.md
    - Stargate Apis:
      - â€¢ Document: pages/develop/api/document.md
      - â€¢ REST: pages/develop/api/rest.md
      - â€¢ graphQL: pages/develop/api/graphql.md
      - â€¢ gRPC: pages/develop/api/grpc.md
    - Languages:
      - â€¢ Java: pages/develop/languages/java.md
      - â€¢ Javascript: pages/develop/languages/javascript.md
      - â€¢ Python: pages/develop/languages/python.md
      - â€¢ GoLang: pages/develop/languages/go.md
      - â€¢ CSharp: pages/develop/languages/csharp.md
      - â€¢ Scala: pages/develop/languages/scala.md
      - â€¢ Rust: pages/develop/languages/rust.md
    - Frameworks:
      - â€¢ Spring: pages/develop/frameworks/spring.md
      - â€¢ Quarkus: pages/develop/frameworks/quarkus.md
      - â€¢ Micronaut: pages/develop/frameworks/micronaut.md
      - â€¢ Lagom: pages/develop/frameworks/lagom.md
      - â€¢ FastAPI: pages/develop/frameworks/fastapi.md
      - â€¢ Flask: pages/develop/frameworks/flask.md
      - â€¢ Django: pages/develop/frameworks/django.md
    - Platform:
      - â€¢ AWS GameSparks: pages/develop/platform/aws-gamesparks.md
      - â€¢ AWS Lambda Functions: pages/develop/platform/aws-lambda-function.md
      - â€¢ Google Cloud Functions: pages/develop/platform/google-cloud-function.md
      - â€¢ Microsoft Azure Functions: pages/develop/platform/azure-function.md
      - â€¢ CircleCI: pages/develop/platform/circleci.md

  - AI/ML ðŸ†•:
    - Overview: pages/aiml/index.md
    - Topics:
      - LLM/GenAI:
        - LangChain: pages/aiml/llm/langchain.md
      - ML Workloads:
        - Feast (â†ª): pages/tools/integration/feast.md

  - Tools/Integrations:
    - Tools List: pages/tools/index.md
    - Databases:
      - â€¢ JanusGraph : pages/tools/databases/janusgraph.md
    - Developers IDE:
      - â€¢ DataStation :  pages/tools/ide/datastation.md
      - â€¢ Eclipse :  pages/tools/ide/eclipse.md
      - â€¢ Gitpod :  pages/tools/ide/gitpod.md
      - â€¢ IntelliJ : pages/tools/ide/intellij.md
      - â€¢ VSCode :  pages/tools/ide/vscode.md
    - Notebooks:
      - â€¢ Jupyter Notebooks :  pages/tools/notebooks/jupyter.md
      - â€¢ DataStax Studio : pages/tools/notebooks/datastax-studio.md
      - â€¢ Apache Zeppelin : pages/tools/notebooks/zeppelin.md
    - Data Visualization:
      - â€¢ Grafana: pages/tools/integration/grafana.md
    - Integration Middlewares:
      - â€¢ Apache Airflow : pages/tools/integration/apache-airflow.md
      - â€¢ Apache Beam : pages/tools/integration/apache-beam-google-dataflow.md
      - â€¢ Apache Flink : pages/tools/integration/flink.md
      - â€¢ Apache Nifi : pages/tools/integration/apache-nifi.md
      - â€¢ Apache Spark : pages/tools/integration/apache-spark.md
      - â€¢ Authorizer : pages/tools/integration/authorizer.md
      - â€¢ Cadence : pages/tools/integration/cadence.md
      - â€¢ Celery : pages/tools/integration/celery.md
      - â€¢ Feast : pages/tools/integration/feast.md
      - â€¢ Google Dataflow : pages/tools/integration/apache-beam-google-dataflow.md
      - â€¢ HashiCorp Vault : pages/tools/integration/vault.md
      - â€¢ Liquibase : pages/tools/integration/liquibase.md
      - â€¢ Pentaho Data Integration : pages/tools/integration/pentaho.md
      - â€¢ Quine : pages/tools/integration/quine.io.md
      - â€¢ StepZen : pages/tools/integration/stepzen.md
      - â€¢ Strapi : pages/tools/integration/strapi.md
      - â€¢ Temporal : pages/tools/integration/temporal.md
    - Plugins:
      - â€¢ HashiCorp Vault : pages/tools/plugins/astradb-vault-plugin.md
      - â€¢ Github Actions : pages/tools/plugins/github-actions.md
  - Sample App Gallery:
    - â€¢ Sample Application Gallery : pages/gallery/index.md
  - Contact Us:
    - â€¢ Contact Us : pages/contact/index.md
  
# ------------------------------------------------------
# Settings
# ------------------------------------------------------

# Project information
site_name: Awesome-Astra
site_url: https://awesome-astra.github.io
site_author: Cedrick Lunven
site_description: >-
 Your Wiki to implement Awesome Applications with Astra

# Repository
repo_name: awesome-astra/docs
repo_url: https://github.com/awesome-astra/docs
edit_uri: ""

# Theme
theme:
 name: material
 language: en

 favicon: img/favicon.svg
 logo: img/favicon.ico
 custom_dir: docs/overrides

 features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
 palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

 extra_javascript:
   - /assets/javascripts/carousel.js

 include_search_page: false
 search_index_only: true

# Markdown Support
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - fontawesome_markdown
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  #- pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - git-revision-date
  #- render_swagger

# Customization
extra:
  analytics:
    provider: google
    property: G-MDYTQ5XG33
  social:
    - icon: fontawesome/brands/discord
      link: https://dtsx.io/discord
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/datastax
    - icon: fontawesome/brands/github
      link: https://github.com/datastaxdevs
    - icon: fontawesome/brands/medium
      link: https://datastax.medium.com/
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/datastaxdevs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/datastax
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCAIQY251avaMv7bBv5PCo-A
