# ------------------------------------------------------
# Page tree
# ------------------------------------------------------
nav:
  - index.md
  - Getting Started:
    - Getting Started With Astra: pages/astra/index.md
    - Astra Core:
      - ‣ Create Account: pages/astra/create-account.md
      - ‣ Create Token: pages/astra/create-token.md
    - AstraDB:
      - ‣ Create Database: pages/astra/create-instance.md
      - ‣ Secure Connect Bundle: pages/astra/download-scb.md
      - ‣ Resume a database: pages/astra/resume-db.md
      - ‣ Multi Regions: pages/astra/multi-regions.md
      - ‣ CQL Proxy: pages/astra/cqlproxy.md
      - ‣ FAQ: pages/astra/faq.md
    - Astra Streaming:
      - ‣ Create Topic: pages/astra/create-topic.md

  - Data Management:
    - Home: pages/data/index.md
    - Load Data:
      - ‣ Astra Data Loader: pages/data/load/astra-data-loader.md
      - ‣ DSBulk: pages/data/load/dsbulk.md
      - ‣ NoSQL Bench: pages/data/load/nosqlbench.md
    - Explore Data:
      - ‣ Cqlsh: pages/data/explore/cqlsh.md
      - ‣ Netflix Data Explorer : pages/data/explore/netflix-data-explorer.md
      - ‣ Datagrip: pages/data/explore/datagrip.md
      - ‣ DBSchema: pages/data/explore/dbschema.md
      - ‣ DBeaver: pages/data/explore/dbeaver.md
      - ‣ Grafana: pages/tools/integration/grafana.md
      - ‣ MindsDB: pages/data/explore/mindsdb.md
      - ‣ Presto: pages/data/explore/presto.md
      - ‣ TablePlus: pages/data/explore/tableplus.md
      - ‣ Trino: pages/data/explore/trino.md
    - Data Modelling:
      - ‣ Kashliev KDM: http://kdm.kashliev.com/

  - Develop with Astra:
    - List: pages/develop/index.md
    - Stargate Apis:
      - • Document: pages/develop/api/document.md
      - • REST: pages/develop/api/rest.md
      - • graphQL: pages/develop/api/graphql.md
      - • gRPC: pages/develop/api/grpc.md
    - Languages:
      - • Java: pages/develop/languages/java.md
      - • Javascript: pages/develop/languages/javascript.md
      - • Python: pages/develop/languages/python.md
      - • GoLang: pages/develop/languages/go.md
      - • CSharp: pages/develop/languages/csharp.md
      - • Scala: pages/develop/languages/scala.md
      - • Rust: pages/develop/languages/rust.md
    - Frameworks:
      - • Spring: pages/develop/frameworks/spring.md
      - • Quarkus: pages/develop/frameworks/quarkus.md
      - • Micronaut: pages/develop/frameworks/micronaut.md
      - • Lagom: pages/develop/frameworks/lagom.md
    - Platform:
      - • AWS Lambda Functions: pages/develop/platform/aws-lambda-function.md
      - • Google Cloud Functions: pages/develop/platform/google-cloud-function.md

  - Third-Party Tools:
    - Tools List: pages/tools/index.md
    - Databases:
      - • JanusGraph : pages/tools/databases/janusgraph.md
    - Developers IDE:
      - • DataStation :  pages/tools/ide/datastation.md
      - • Eclipse :  pages/tools/ide/eclipse.md
      - • Gitpod :  pages/tools/ide/gitpod.md
      - • IntelliJ : pages/tools/ide/intellij.md
      - • VSCode :  pages/tools/ide/vscode.md
    - Notebooks:
      - • Jupyter Notebooks :  pages/tools/notebooks/jupyter.md
      - • DataStax Studio : pages/tools/notebooks/datastax-studio.md
      - • Apache Zeppelin : pages/tools/notebooks/zeppelin.md
    - Data Visualization:
      - • Grafana: pages/tools/integration/grafana.md
    - Integration Middlewares:
      - • Apache Airflow : pages/tools/integration/apache-airflow.md
      - • Apache Nifi : pages/tools/integration/apache-nifi.md
      - • Apache Spark : pages/tools/integration/apache-spark.md
      - • Authorizer : pages/tools/integration/authorizer.md
      - • Cadence : pages/tools/integration/cadence.md
      - • Celery : pages/tools/integration/celery.md
      - • Feast : pages/tools/integration/feast.md
      - • HashiCorp Vault : pages/tools/integration/vault.md
      - • Liquibase : pages/tools/integration/liquibase.md
      - • Pentaho Data Integration : pages/tools/integration/pentaho.md
      - • Quine : pages/tools/integration/quine.io.md
      - • StepZen : pages/tools/integration/stepzen.md
      - • Temporal : pages/tools/integration/temporal.md
    - Plugins:
      - • HashiCorp Vault : pages/tools/plugins/astradb-vault-plugin.md

# ------------------------------------------------------
# Settings
# ------------------------------------------------------

# Project information
site_name: Awesome-Astra
site_url: https://awesome-astra.github.io
site_author: Cedrick Lunven
site_description: >-
 Your Wiki to implement Awesome Applications with Astra

# Repository
repo_name: awesome-astra/docs
repo_url: https://github.com/awesome-astra/docs
edit_uri: ""

# Theme
theme:
 name: material
 language: en

 favicon: img/favicon.svg
 logo: img/favicon.ico
 custom_dir: docs/overrides

 features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
 palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

 extra_javascript:
   - /assets/javascripts/carousel.js

 include_search_page: false
 search_index_only: true

# Markdown Support
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - fontawesome_markdown
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  #- pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - git-revision-date
  #- render_swagger

# Customization
extra:
  analytics:
    provider: google
    #property: G-ZMZXZME49E
    property: G-MDYTQ5XG33
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCAIQY251avaMv7bBv5PCo-A
    - icon: fontawesome/brands/github
      link: https://github.com/clun
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/clunven
    - icon: fontawesome/brands/discord
      link: https://dtsx.io/discord
